sudo: required
dist: trusty

matrix:
  include:

  - os: linux
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - gcc-4.9
        - g++-4.9
        - cmake
        - valgrind
        - libtool
        - pkg-config
    before_script:
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - source $FEATHER_CPP/ci/before_script_travis.sh
    - cmake -DCMAKE_CXX_FLAGS="-Werror -O0 -coverage" $FEATHER_CPP
    script:
    - make lint
    - make -j4 || exit 1
    - valgrind --tool=memcheck --leak-check=full --error-exitcode=1 ctest
    env: TRAVIS_LANG=C++
    after_success:
    - bash <(curl -s https://codecov.io/bash) -p $BUILD_DIR/src/feather/CMakeFiles/feather.dir -x gcov-4.9

  - os: osx
    language: cpp
    compiler: clang
    before_script:
    - source $FEATHER_CPP/ci/before_script_travis.sh
    - cmake -DCMAKE_CXX_FLAGS="-Werror" $FEATHER_CPP
    script:
    - make -j4 || exit 1
    - ctest
    env: TRAVIS_LANG=C++

  - os: linux
    language: r
    compiler: gcc
    r_binary_packages:
      - BH
      - crayon
      - DBI
      - dplyr
      - lazyeval
      - magrittr
      - praise
      - Rcpp
      - testthat
    before_install:
    - cd R
    - ./configure
    after_success:
    - Rscript -e 'install.packages("covr"); covr::codecov()'
    env: TRAVIS_LANG=R

  - os: linux
    language: python
    python: 2.7
    compiler: gcc
    before_install:
    - cd python
    - ln -s ../cpp/src src
    install:
    - pip install cython
    - pip install -r requirements.txt
    script: python setup.py test
    env: TRAVIS_LANG=python

  - os: linux
    language: python
    python: 3.4
    compiler: gcc
    before_install:
    - cd python
    - ln -s ../cpp/src src
    install:
    - pip install cython
    - pip install -r requirements.txt
    script: python setup.py test
    env: TRAVIS_LANG=python

  - os: linux
    language: python
    python: 3.5
    compiler: gcc
    before_install:
    - cd python
    - ln -s ../cpp/src src
    install:
    - pip install codecov
    - pip install cython
    - pip install -r requirements.txt
    script: coverage run setup.py test
    env: TRAVIS_LANG=python
    after_success:
      codecov

before_install:
- export FEATHER_CPP=$TRAVIS_BUILD_DIR/cpp
- mkdir $HOME/build_dir
- cd $HOME/build_dir
